# Generated by Django 5.2.3 on 2025-07-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=100)),
                ('organization_name', models.CharField(max_length=50)),
                ('registration_timestamp', models.DateTimeField(auto_now_add=True)),
                ('old_password', models.CharField(blank=True, max_length=50, null=True)),
                ('last_login_timestamp', models.DateTimeField(blank=True, null=True)),
                ('login_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('login_otp_sent_timestamp', models.DateTimeField(blank=True, null=True)),
                ('login_otp_expiry_timestamp', models.DateTimeField(blank=True, null=True)),
                ('forgot_password_timestamp', models.DateTimeField(blank=True, null=True)),
                ('reset_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('reset_otp_sent_timestamp', models.DateTimeField(blank=True, null=True)),
                ('reset_otp_expiry_timestamp', models.DateTimeField(blank=True, null=True)),
                ('password_reset_timestamp', models.DateTimeField(blank=True, null=True)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('failed_otp_attempts', models.IntegerField(default=0)),
                ('account_blocked_until', models.DateTimeField(blank=True, null=True)),
                ('otp_blocked_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
