# Generated by Django 5.2.4 on 2025-07-09 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', max_length=50)),
                ('builder', models.CharField(blank=True, choices=[('pre-built', 'Use Pre-Built Assessment'), ('library-questions', 'Start Using Library Questions')], max_length=50, null=True)),
                ('level', models.CharField(blank=True, choices=[('fresher', 'Fresher (0-1 Year)'), ('intermediate', 'Intermediate (1-3 Years)'), ('experience', 'Experience (3+ Years)')], max_length=50, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('total_time', models.DurationField(default='00:30:00')),
                ('total_points', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('topic', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('MSQ', 'Multiple Selection'), ('Text', 'Text Entry'), ('Code', 'Coding'), ('Upload', 'File Upload')], default='MCQ', max_length=10)),
                ('difficulty', models.CharField(choices=[('Basic', 'Basic'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Intermediate', max_length=20)),
                ('depth_of_knowledge', models.CharField(choices=[('Recall', 'Recall & Reproduction'), ('Skill', 'Skills/Concepts'), ('Strategic', 'Strategic Thinking'), ('Extended', 'Extended Thinking')], default='Skill', max_length=20)),
                ('domain', models.CharField(choices=[('TECH', 'TECH'), ('NON-TECH', 'NON-TECH')], default='TECH', max_length=10)),
                ('time_limit', models.DurationField(default='00:05:00')),
                ('points', models.PositiveIntegerField(default=2)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questionapi.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questionapi.question')),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('reviewer_type', models.CharField(choices=[('external', 'External Reviewer'), ('team', 'Team Member')], max_length=20)),
                ('assigned_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewers', to='questionapi.assessment')),
            ],
        ),
    ]
